# Generated by Django 5.1.6 on 2025-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('key_skills', models.CharField(max_length=100, null=True)),
                ('salary_from', models.IntegerField(null=True)),
                ('salary_to', models.IntegerField(null=True)),
                ('salaty_currency', models.CharField(max_length=10, null=True)),
                ('area_name', models.CharField(max_length=100, null=True)),
                ('published_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
