# Generated by Django 5.1.6 on 2025-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
