# Generated by Django 5.1.6 on 2025-02-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0002_alter_vacancies_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='salaty_currency',
            new_name='salary_currency',
        ),
    ]
