# Generated by Django 5.1.6 on 2025-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0003_rename_salaty_currency_vacancies_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='salary_from',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary_to',
            field=models.FloatField(null=True),
        ),
    ]
