# Generated by Django 5.1.6 on 2025-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0004_alter_vacancies_salary_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='key_skills',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
