# Generated by Django 5.1.6 on 2025-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0005_alter_vacancies_key_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='key_skills',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
