# Generated by Django 5.1.6 on 2025-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0006_alter_vacancies_key_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
