# Generated by Django 5.1.6 on 2025-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0007_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
