# Generated by Django 5.1.6 on 2025-02-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0008_remove_exchangerate_rate_alter_exchangerate_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('graph', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
