# Generated by Django 5.1.6 on 2025-02-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0009_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='graph',
            field=models.TextField(null=True),
        ),
    ]
